### ISSUE TITLE
[Bug]: jumbo size menu & setting font

### ISSUE THREAD

**Issue by the-liquid-metal** [vzhd1701/gridplayer#10]
### GridPlayer version

0.1.5

### What OS are you using?

Windows

### OS Version / Linux distribution

win10

### Bug description

the menu & setting font are to big.

**Comment by vzhd1701** [comment]
Could you please show me screenshot of your windows?

**Comment by the-liquid-metal** [comment]
screen: 1920x1080

![image](https://user-images.githubusercontent.com/238188/144158384-2657abc2-e146-4f8a-836c-2ca0519894c9.png)


![image](https://user-images.githubusercontent.com/238188/144158557-f08c542c-3d9c-4a00-a232-8ab0c2c31ae8.png)

note: for comparison: normal font size in other app is included.

**Comment by vzhd1701** [comment]
Please check out new release, the UI should scale properly now.

**Comment by the-liquid-metal** [comment]
Much Better. Thanks.
