### ISSUE TITLE
[Question] how to jump to other movie without hovering the mouse?

### ISSUE THREAD

**Issue by the-liquid-metal** [vzhd1701/gridplayer#11]
in order to activate the movie, i have to hover my mouse until the top and buttom bar appears.
how to jump to other movie without hovering the mouse (i.e. by keyboard)?

**Comment by vzhd1701** [comment]
I am afraid it's not possible at the moment. I'll need to rethink the focusing mechanism to make keyboard switching possible.

**Comment by vzhd1701** [comment]
I changed focusing logic. Now you can switch focus using TAB.
