### ISSUE TITLE
[Feature request]: Shuffle next video when pressing Pgdown or Pgup 

### ISSUE THREAD

**Issue by mfarnco2000** [vzhd1701/gridplayer#119]
### Suggestion

Hi i just downloaded gridplayer and it's amazing, only thing I noticed is that the videos will not shuffle when I press Pgdown or Pgup. I am wondering if I missing something and this already exists in the program. Right now I have to let the video finish in order to get it to shuffle to the next.  Thanks for the great program.

**Comment by vzhd1701** [comment]
Works in version 0.5.0

**Comment by mfarnco2000** [comment]
Yeah same I can't get a random when using PgDown or PgUp. I am using the 0.5.0 version. I do have the 'repeat directory shuffle" on. I still have to wait for the video to finish to get a random shuffle.
