### ISSUE TITLE
[Feature request]: Add option to persist the top and bottom bar

### ISSUE THREAD

**Issue by the-liquid-metal** [vzhd1701/gridplayer#12]
### Suggestion

Sometimes we need to adjust other movies relative to the one, or need to document time of each movies.
It is tedious to hover each movies each time we do that.

**Comment by vzhd1701** [comment]
Will do in the next release. For now you can set video overlay timeout to 60s in settings.

**Comment by vzhd1701** [comment]
Done. Now you have setting to make overlay persistent.
![Clipboard Image (2)](https://user-images.githubusercontent.com/5212766/147658571-67af18e8-ea8e-4f19-9e04-1af1724b91e7.png)
