### ISSUE TITLE
[Feature request]: Sync zoom in/out

### ISSUE THREAD

**Issue by teijiIshida** [vzhd1701/gridplayer#124]
### Suggestion

Could you add an option to allow zoom in/out syncing (of multiple videos simultaneously)? Currently, we have to manually zoom in/out each video separately. It'd be great if they can be in sync.

**Comment by LiberiFatali** [comment]
How about Right click, choose [ALL] --> Video --> Zoom?

**Comment by teijiIshida** [comment]
I use that. But it only sync for zoom OUT (doesn't sync zoom IN, doesn't sync for zoom reset either).

**Comment by vzhd1701** [comment]
You should use + and - from the numpad area. When you press Shift + + from the upper row you actually press Shift + = which turns in a single +.

**Comment by teijiIshida** [comment]
> 

My keyboard is TKL, so I don't have the numpad keys. How about a way to rebind keys?

**Comment by vzhd1701** [comment]
This will require implementing hotkey editor, merging with #159
