### ISSUE TITLE
easy translate for simple Chinese 

### ISSUE THREAD

**Issue by SaintChangeTheWorld** [vzhd1701/gridplayer#125]
### Suggestion

can you update your code of  Right mouse button？
change them like this pictures。
<img width="189" alt="微信图片_20230504174153" src="https://user-images.githubusercontent.com/102570793/236169262-9f317543-a550-4002-9a5f-ecbdad1f2fac.png">
<img width="210" alt="微信图片_20230504174225" src="https://user-images.githubusercontent.com/102570793/236169387-792be24f-ca8a-41fd-8708-0f39a2647cfa.png">
change this English word as simple Chinese in this pictures of red word。
you CAN use the orc software to read the red word in this pictures。

**Comment by sum1game** [comment]
https://github.com/sum1game/gridplayer/tree/master/resources/translations
我制作了简体中文的.ts文件，应该怎么添加进软件中？
How can I add the .ts file of simplified Chinese that I made into the software?

**Comment by LiberiFatali** [comment]
I think the translation project is here:  https://crowdin.com/project/gridplayer

**Comment by sum1game** [comment]
Replying to the friend above, yes, there is this project, but the author may have not been paying attention to it for a long time. Many translations in different languages have been completed, and the only thing left is to load them into the software. @ @LiberiFatali @vzhd1701

**Comment by vzhd1701** [comment]
I will update the project soon.
