### ISSUE TITLE
[Bug]: App opens but dropping one or more videos shows "Buffering" placeholder and app gets unresponsive 

### ISSUE THREAD

**Issue by porg** [vzhd1701/gridplayer#126]
## Environment
- GridPlayer 0.4.3 (app bundle installed from DMG)
- macOS 11.7.4 Big Sur
- MacBook Pro (Mid 2014)
- iGPU Intel Iris Pro
- dGPU NVIDIA GeForce GT 750M 2 GB
  - Known for buggy drivers on macOS 11 Big Sur (last supported OS, that I still run now)
  - In daily life I have no issues with it but it is [known to be buggy](https://forums.macrumors.com/threads/rendering-glitches-only-in-specific-apps-photos-and-safari-on-mbp-15-mid-2014-when-dgpu-active-in-macos-11-big-sur.2284320/?post=29598481#post-29598481).
  - But what I saw from system.log, your app seems to try to get GPU drivers which are not even present on my system

## Bug
![gridplayer totally unresponsive](https://github.com/vzhd1701/gridplayer/assets/737143/aaf08dca-5c35-4465-9ae6-2ef8f564cbe9)

## Reproduction
- Starting the app works. Shows window with "Drag and drop media files or URLs here."
- I then drop 1 or 2 videos: Screen recording as MOV (h264, no audio track) + its Handbrake transcoded counterpart MP4 (h264, variable bit rate at constant quality RF 28)
- The app shows the placeholder per each video (graphic + text "Buffering…")
- And then becomes unresponsive immediately
- I have to force quit.

## Whatever iGPU / dGPU mode I run in, the bug is always the same
- With external monitor connected (forces dGPU to run)
- With my background deamon that accesses the dGPU on or off (Snagit Helper, deamon runnung for instant always ready screenshots/video recording)
- Only iGPU running, with no external display and no app with a dGPU dependence running

### Log excerpt

```shell
system.log during using gridplayer

# Launching app - Idle until I have my videos ready fro drag-n-drop

May 13 16:29:30 mbpr com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0D000000-0600-0000-0000-000000000000[52396]): Service exited due to SIGKILL | sent by mds[120]

# Dropping 2 videos: Screen recording as MOV (h264, no audio track) + its Handbrake transcoded counterpart MP4 (h264, variable bit rate at constant quality RF 28)

# Shows video placeholder with message "Buffering" per each video dropped (so 2 in total) - But becomes unresponsive immediately "spinning beachball of death" on top of the window

## The following (2+3) lines repeat twice, I guess per each technical video player instance, seems the path to the GPU driver is not found.

May 13 16:29:52 mbpr VTDecoderXPCService[52402]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
May 13 16:29:52 mbpr VTDecoderXPCService[52402]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug

May 13 16:29:52 mbpr VTDecoderXPCService[52402]: getattrlist failed for /Library/GPUBundles/AppleIntelHD5000GraphicsVADriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsVADriver: #2: No such file or directory
May 13 16:29:52 mbpr VTDecoderXPCService[52402]: getattrlist failed for /Library/GPUBundles/GeForceVADriver.bundle/Contents/MacOS/GeForceVADriver: #2: No such file or directory
May 13 16:29:52 mbpr VTDecoderXPCService[52402]: getattrlist failed for /Library/GPUBundles/AppleIntelHSWVA.bundle/Contents/MacOS/AppleIntelHSWVA: #2: No such file or directory


May 13 16:29:52 mbpr VTDecoderXPCService[52402]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
May 13 16:29:52 mbpr VTDecoderXPCService[52402]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug

May 13 16:29:52 mbpr GridPlayer[52398]: getattrlist failed for /System/Library/Extensions/AppleIntelHD5000GraphicsGLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsGLDriver: #2: No such file or directory
May 13 16:29:52 mbpr GridPlayer[52398]: getattrlist failed for /System/Library/Extensions/GeForceGLDriver.bundle/Contents/MacOS/GeForceGLDriver: #2: No such file or directory
May 13 16:29:52 mbpr GridPlayer[52398]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory


...

# Omitted some lines where I was 100% sure they came from something else totally unrelated

# About the next line I don't know if this is still related to gridplayer of coming from something else
May 13 16:31:19 mbpr com.apple.appkit.xpc.openAndSavePanelService[52415]: assertion failed: 20G1120: libxpc.dylib + 88455 [AB7BBDA1-3AC6-3832-8AB1-F3BFB7A0E5EC]: 0x89




# Force quitting

May 13 16:32:33 mbpr com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.vzhd1701.gridplayer.53138580.53138686(501)> [38658]
May 13 16:32:36 mbpr syslogd[90]: ASL Sender Statistics
```

**Comment by vzhd1701** [comment]
Looks like a libVLC problem, I'll need to update libVLC and test it. I can't get my hands on working macOS at the moment, this will have to wait, sorry.

**Comment by porg** [comment]
1. Thanks for giving a quick initial reply.
2. Besides the bug, in general is macOS 11 Big Sur supported by gridplayer. and will remain so for the near future?
3. No hurry. I'm subscribed to this bug, and will get notified whenever you make progress on this. Will check it out then.

**Comment by porg** [comment]
Last but not least: If the problem is that you don't have a mac device available to you currently, I could help out, if it is just a matter of replacing a library file somewhere, and no other adaptions or compilations are needed.

**Comment by vzhd1701** [comment]
Should be fixed in version 0.5.1. I tested on Monterey. Please try it and tell how it works for you.

**Comment by vzhd1701** [comment]
Have you tried running this command?
```
sudo xattr -rd com.apple.quarantine /Applications/GridPlayer.app
```

**Comment by porg** [comment]
Now ran it.
- App launched.
- Dropping two videos on it loaded them and playback works!
- Hurray, now finally I have the possibility to explore this app. Thanks!

**Comment by neurodiverseEsoteric** [comment]
Hi, I'm having a similar issue but on CachyOS
