### ISSUE TITLE
[Feature request]: Some menus don't translate

### ISSUE THREAD

**Issue by mikehendry** [vzhd1701/gridplayer#128]
### Suggestion

as shown below:
![01](https://github.com/vzhd1701/gridplayer/assets/28629037/2b87b470-f32c-43cf-b424-2105e1ff1d9f)
![02](https://github.com/vzhd1701/gridplayer/assets/28629037/8488849a-c843-421b-b3ee-cfddfc0adfb6)

**Comment by vzhd1701** [comment]
Sorry, I forgot to rebuild the base strings file before the update. It's updated and uploaded to [crowdin](https://crowdin.com/project/gridplayer) for translation now.
