### ISSUE TITLE
[Feature request]: Able to rename movie title

### ISSUE THREAD

**Issue by the-liquid-metal** [vzhd1701/gridplayer#13]
### Suggestion

If we arrange single movie multipe time, it is less usefull to have identical title.
The "Renaming title" capability along with the "persistent bar" feature is useful for analytical tasks.

Don't forget to add option to change background and font color in order to adjust with the movie.

**Comment by vzhd1701** [comment]
Done. Now you can set custom name & color for each video.
![Clipboard Image (3)](https://user-images.githubusercontent.com/5212766/147658682-aed6de32-407f-4dd5-8b83-0e6cdd494266.png)
![Clipboard Image (4)](https://user-images.githubusercontent.com/5212766/147658770-7df67d1e-af08-4e88-9050-9c3b8b6fb7cd.png)
