### ISSUE TITLE
My.mail.ru bug

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#132]
### GridPlayer version

v0.5.0

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Hello, you have kind and generosity a year ago to solve "my.mail.ru" problem, thank you :) i notice now that sadly this problem comes back and i can't play this video :

https://my.mail.ru/v/thisishorosho_tv/video/7/1248.html

We hope this problem will be solved please , thank you very much :)

I also noticed that GridPlayer did not try to use streamlink when yt-dlp failed, should we install streamlink ourselves or streamlink is already integrated with GridPlayer ?

**Comment by vzhd1701** [comment]
Your link works OK on my side. What error are you getting? Can you show me the log?

**Comment by trimechee** [comment]
I just tried it and it works! it surprises me because earlier it didn't work ..... thank you very much and sorry :)
