### ISSUE TITLE
Sibnet bug

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#135]
### GridPlayer version

v0.5.0

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Hello, Sibnet platform is a famous streaming paltform that contains many videos ans the playback is smooth eve for weak connection and used by many websies like this site :

https://vostfree.ws/1378-dead-mount-death-play-ddl-streaming-1fichier-uptobox.html

i hope to play Sibnet videos with our beloved GridPlayer, i can play sibnet video like this video :

https://video.sibnet.ru/video5128213-Dead_Mount_Death_Play_01_VF/?utm_source=player&utm_medium=video&utm_campaign=EMBED

with another video player that has graphical interface of mpv, but i can't play this sibnet video with GridPlayer E even that sibnet is officially supported by yt-dlp !

https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

I even manipulated the html code of the video:

"<iframe width="640" height="384" src="https://video.sibnet.ru/shell.php?videoid=5128213" frameborder="0" scrolling="no" allowfullscreen></iframe> "

by removing unnecessary things to put only the pure sibnet url address: "https://video.sibnet.ru/shell.php?videoid=5128213" but GridPlayer does not succeed in playing the sibnet video, we hope that this bug will be solved, thank you :)

**Comment by vzhd1701** [comment]
This URL plays OK on my side.

https://video.sibnet.ru/video5128213-Dead_Mount_Death_Play_01_VF/?utm_source=player&utm_medium=video&utm_campaign=EMBED

What error are you getting?

**Comment by trimechee** [comment]
I try now and it works ! maybe it didn't work at first because i disabled several network services and options in windows to perform tricks to make my pc even faster...now i re-enabled those services and it works , thanks a lot :)
