### ISSUE TITLE
myvi bug

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#136]
### GridPlayer version

v0.5.0

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Hello, myvi streaming platform is officially supported by yt-dlp, but Gridplayer can't play myvi video :

https://www.myvi.top/idffoo?v=hi3pnosn6nwwzp4zdei1cz7iar

we hope this problem will be fixed, thank you :)

**Comment by vzhd1701** [comment]
yt-dlp supports myvi.ru, not myvi.top, you can check [here](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/myvi.py).

**Comment by trimechee** [comment]
Interesting ! Thank you ! 💯
