### ISSUE TITLE
[Bug]: Add support for relative paths

### ISSUE THREAD

**Issue by lyolve** [vzhd1701/gridplayer#138]
### Suggestion

I wrote a python script choosing random video file to play.
Potplayer can work with "D:\software\PotPlayer64\PotPlayerMini64.exe xxx.mp4"
but gridplayer do not have this option, Pop-up window with “No supported files or URLS” instead
Any suggestions？

**Comment by lyolve** [comment]
![image](https://github.com/vzhd1701/gridplayer/assets/43743367/e75a71ed-18ae-4673-a256-20e3983dc4fa)

**Comment by vzhd1701** [comment]
Sorry, GridPlayer doesn't support relative paths. I will fix it in the next version. For now just convert the filename to absolute path before calling GridPlayer.

**Comment by vzhd1701** [comment]
Should be fixed in version 0.5.1
