### ISSUE TITLE
Impossible to play streaming mp4 video

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#139]
### GridPlayer version

v0.5.0

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Hello, i tried to play this streaming mp4 video but i can't when i use GridPlayer, but when i use other players like vlc player and potplayer, i can :

https://weststor-5-y-1-t-v.vmrest.space/xqx2pizforokjiqbteocjikhwvlpb5kb6mh4llastzayijk5yudymeqj3wuq/h3dvyvwnnvqg.mp4

the link of the video come from this site when i click "now download HD",

https://vidmoly.me/dl/h3dvyvwnnvqg

and this link come from this streaming site when i choose first player and i use firefox browser without adblock but with adguard dns , because when i use adblocker like ublock origin, the download link doesn't appear :

https://v3.voiranime.com/anime/dragon-ball-vf/dragon-ball-028-vf/

**Comment by LiberiFatali** [comment]
I downloaded the file, and I can play it with gridplayer.

**Comment by trimechee** [comment]
@LiberiFatali  No, I hope to play the file directly without waiting for the end of the download, I put the url address of the video and I play this file directly without waiting for the end of  the download as I can do with potplayer and vlc player, this link comes from a site streaming which offers streaming and a video download link, I used firefox which opens this link in a new tab and the video works so I copied the link and I want to use a media player to play the video and not the browser because with the media player, I can full buffer all the video with my connection which can become weak in addition the media player improves the video quality....

**Comment by LiberiFatali** [comment]
@trimechee 
I understand that you could get the direct link to mp4 file (i.e https://weststor-5-y-1-t-v.vmrest.space/xqx2pizforokjiqbteocjikhwvlpb5kb6mh4llastzayijk5yudymeqj3wuq/h3dvyvwnnvqg.mp4). 

You may try go to Setting (right-click), and set **resolver_priority** to **direct**, then using direct link above to play

**Comment by trimechee** [comment]
@LiberiFatali  Wonderful fantastic !! 💯  Thank you very much for your precious help :)

**Comment by trimechee** [comment]
Hello, @LiberiFatali, did you know if the great GridPlayer support hlsdl ? https://github.com/selsta/hlsdl 

because users says hlsdl solve some bugs in ffmpeg....

**Comment by trimechee** [comment]
@LiberiFatali "The bug : " ......HLSDL appears working much better than ffmpeg in these cases.
Hlsdl is public and the source code available.
The stream plays almost immediately and is stable. No errors or buffering.
Using ffmpeg for the download step gives a very long intial delay and is not very stable.
so I assume that the new crypto+hls RAI flows are badly handled by ffmpeg based players now.....

the video is choppy and unable to buffer enough for a fluid vision. Parole has no problem.

FFmpeg is not good for HLS streams, but I watched a lot of various HLS streams without any problems. The main problem is that FFmpeg downloads all streams (many video sizes at once), so you can watch only HLS stream with single video size"
