### ISSUE TITLE
[Bug]: Auto pause doesn't always work.

### ISSUE THREAD

**Issue by the-liquid-metal** [vzhd1701/gridplayer#14]
### GridPlayer version

0.1.6

### What OS are you using?

Windows

### OS Version / Linux distribution

win10

### Bug description

Auto pause only works if we click it own button in taskbar (i.e. to hide its own window).
But if we click other app button in taskbar (or anything which make it inactive window), the movies are still played.

**Comment by vzhd1701** [comment]
Other players behave in similar way. If window becomes inactive the don't pause. They pause only when you minimize the window.
