### ISSUE TITLE
 Vlc player will not play videos with either ads or copyright-claimed 

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#152]
### Suggestion

Hello, it seems that Vlc player will not play videos with either ads or copyright-claimed : 
https://forum.videolan.org/viewtopic.php?p=483226#p483226

and the solution to fix this problem is to replace the default lua files with these lua files found on the vlc player github page :

https://github.com/videolan/vlc/blob/master/share/lua/playlist/youtube.lua

https://github.com/videolan/vlc/tree/master/share/lua/playlist

can our beloved GridPlayer do this for youtube and for all supported sites and replace the default lua files with the new ones  therefore we can playback videos that contain ads ? Thanks a lot !

**Comment by vzhd1701** [comment]
The topic you are referencing is from 2018. Anyway all youtube links parsing is done by yt-dlp, GridPlayer does not rely on VLC builtin youtube scripts.

**Comment by trimechee** [comment]
Great ! Thank you ! and thanks a lot for the new updated version ! 💯 🥇
