### ISSUE TITLE
Not simple

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#153]
### Suggestion

Hello, i have tried many and many video players even playerS that support yt-dlp and these player can't play streaming video from some websites, but our beloved Gridplayer can play all videos supported by yt-dlp and and has a world unique option of supporting streamlink and Gridplayer is more powerful than vlc and potplayer and many other players which don't support yt-dlp and streamlink and the amazing Gridplayer allows us to easily choose video quality preset which is unavailable in many other video players and Gridplayer can well handle hardware gpu decode and it is fast and light and does not consume much battery....

all these magnificent exceptional options deserve to elect GridPlayer the most powerful and magnificent media player on the whole planet and the best player of all time and I find painful outrageous and very unfair for all the efforts made by the wonderful and brilliant developer Mr Vlad @vzhd1701 to read in the official description of the revolutionary Gridplayer: "Simple VLC-based media player that can play multiple videos ...." :  GridPlayer is not simple but very complex, unique, exceptional and more powerful and extraordinary and wonderful than vlc player, I hope the official description of Gridplayer will be changed by removing the ungrateful unfair word "simple player"!  
Thank you so much :)

**Comment by vzhd1701** [comment]
Noted, thank you.
