### ISSUE TITLE
Hardware (default) mode or "Hardware SP" mode energy

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#154]
### Suggestion

Hello, we would like to know please which hardware decode mode uses less energy and battery and does not cause noisy fans to start, which hardware mode is the most energy efficient : Hardware (default) mode or "Hardware SP" mode ?

 and please what hardware decode mode do you recommend to us when we have a somewhat old notebook like my asus i3 computer bought in 2017 Intel(R) HD Graphics 520 ?

**Comment by vzhd1701** [comment]
I don't recommend using Hardware SP mode, it was implemented as a fallback mechanism to allow running GridPlayer on MacOS. Resource usage depends on the number of videos you are playing simultaneously and their resolution, so just stick with the default mode.

**Comment by trimechee** [comment]
Thank you :)

**Comment by trimechee** [comment]
Sorry to make question again, my graphics card driver has not been updated since 2020 so I am not sure it is ideal if I use hardware acceleration, so I am looking to deactivate this option, please what is the difference in the advanced/video decoder section between software and dumbny? decoding is done at the software level and not at the hardware level? and dumbny completely disables video decoding?

**Comment by vzhd1701** [comment]
Yes, with software mode all video decoding and display is done by CPU, but it is very slow and you will end up with very high CPU load. Your GPU driver version doesn't matter as long as it works OK in your OS. Dummy mode is only meant for development, you won't be able to play anything using it.

**Comment by trimechee** [comment]
Ohh very instructive ! Thank you so much for your so precious advices :) 🥇 💯
