### ISSUE TITLE
[Bug]:  Timed out setting initial state

### ISSUE THREAD

**Issue by gorgeousdays** [vzhd1701/gridplayer#169]
### GridPlayer version

0.5.2

### What OS are you using?

Linux

### OS Version / Linux distribution

Manjaro

### What distribution channel are you using? [LINUX ONLY]

Snap Store

### Bug description

out of time

### Log excerpt

```shell
log:
`2023-08-24 14:40:09,541 (13330) | QT | ERROR | Failed to create wl_display (No such file or directory)
2023-08-24 14:40:09,627 (13330) | gridplayer.main.init_translator | WARNING | Failed to load QT translation for zh_CN
2023-08-24 14:40:32,494 (13330) | QT | warning | QXcbDrag::handleFinished - drop data has expired
2023-08-24 14:42:12,152 (13441) | EventWaiter | error | Waiting for vout timed out after 119 seconds
2023-08-24 14:42:12,153 (13441) | PlayerProcessSingleVLCHW | error | Timed out setting initial state`
```

**Comment by gorgeousdays** [comment]
i install gridplayer follow this article:
https://snapcraft.io/install/gridplayer/arch

**Comment by vzhd1701** [comment]
I tested it on XFCE and it works OK. What version of Manjaro are you running? Plasma, XFCE or Gnome?

**Comment by gorgeousdays** [comment]
Plasma. Thanks for your reply. I solve this by using flatpak.
`flatpak install com.vzhd1701.gridplayer`

> I tested it on XFCE and it works OK. What version of Manjaro are you running? Plasma, XFCE or Gnome?

**Comment by dotbanana** [comment]
Gridplayer Flatpak on Fedora 40 Gnome Wayland not working with Error 
"Timed out setting initial state"

**Comment by papagrant** [comment]
> Gridplayer Flatpak on Fedora 40 Gnome Wayland not working with Error "Timed out setting initial state"

I am running Bazzite which is fedora silverblue and I am getting the same error message. I installed via terminal command (flatpak).
