### ISSUE TITLE
[Feature request]: 3 vertical videos in a row, please! 🙏

### ISSUE THREAD

**Issue by frgonzalezb** [vzhd1701/gridplayer#17]
### Suggestion

First of all, thank you so much for this amazing player (and it's free!). 🤩

**My request:** I've found vertical videos (those made with phones) are severely cropped because of the grid based on regular horizontal videos, making it almost unusable except for 2 simultaneous vertical ones (with some less severe cropping, though).

On the other hand, thanks to some _compilation_ videos around the web, I've noticed that **3 vertical videos fit amazingly well when they're in a row (side-by-side)** on a regular horizontal widescreen resolution. For example, three 9:16 videos in a row make a 27:16 horizontal video, which is very close to regular 16:9 widescreen resolution, and the loss image portions for each video due to cropping is pretty negligible.

**Is there a way to bring that feature soon on the following releases?** 🙏

Thanks again and have a good day. 😎

**Comment by vzhd1701** [comment]
Thank you for your feedback and thank you for using my program! 😄

It can already do that! Just set the grid size to 3 in `Rows First` mode for example and it will [tile 3 vertical videos in a row](https://user-images.githubusercontent.com/5212766/144986767-248bb8fd-8ec2-42d5-a4b8-56b47974588e.png) without cropping them.

![Clipboard Image (1)](https://user-images.githubusercontent.com/5212766/144987072-404cc31f-4dd6-4b68-9e44-41377f36aef9.png)
