### ISSUE TITLE
[Feature request]: prevent accidentally mouse click and scroll

### ISSUE THREAD

**Issue by the-liquid-metal** [vzhd1701/gridplayer#18]
### Suggestion

The default mouse click and scroll is useful if we just want to enjoy the show without being distracted by the state of the movie.
This behavior is annoying when we want the state of all movies to not change while doing something.

**Comment by vzhd1701** [comment]
Do you mean you want a function that will disable mouse interaction with the player? Like locked mode?

**Comment by the-liquid-metal** [comment]
Yes. Only left button will be locked.

**Comment by vzhd1701** [comment]
It would seem logical to lock keyboard control also. Like lock video from jumping or changing state by the user. Or should it still be available?
Another question - should this lock be set for each video or playlist-wide?

**Comment by the-liquid-metal** [comment]
> It would seem logical to lock keyboard control also. Like lock video from jumping or changing state by the user. Or should it still be available?

Yes. Please read last paragraph of #21 ([Feature request]: balancing keyboard functionality between "all movies" and "single movie" enhancement)

> Another question - should this lock be set for each video or playlist-wide?

playlist-wide.

**Comment by vzhd1701** [comment]
I added two new playlist settings that implement this

![image](https://user-images.githubusercontent.com/5212766/175575553-a0d0fe7d-9219-48a7-b7db-fbeda63236da.png)
