### ISSUE TITLE
[Feature request]: Why I have installed the VLC player but when I run app by Python(poetry environment) it show VLC player is required!

### ISSUE THREAD

**Issue by huskyloveme** [vzhd1701/gridplayer#188]
### Suggestion

![image](https://github.com/vzhd1701/gridplayer/assets/27890567/6663fe34-370c-4fdf-aa71-c865a84921ce)
![image](https://github.com/vzhd1701/gridplayer/assets/27890567/688b9a2a-965a-4872-8650-d222e9949f6b)

**Comment by vzhd1701** [comment]
`vlc` library searches for VLC installation by looking up `Software\VideoLAN\VLC` in the registry, falling back to `C:\Program Files\VideoLan\VLC\libvlc.dll` in case it can't find it there. You can see the logic [here](https://github.com/oaubert/python-vlc/blob/587d6263ba3176e158b6804f7457163ba1bed12c/generated/3.0/vlc.py#L149C43-L149C66).

**Comment by huskyloveme** [comment]
Thank you for your quick response! The issue has been fixed :D
