### ISSUE TITLE
[Feature request]: Add "Jump to" in seconds instead of percentage

### ISSUE THREAD

**Issue by WilliUreta** [vzhd1701/gridplayer#2]
### Suggestion

If you are watching 2 videos of the same event but with different lengths, jumping in percentages makes them not synched.
Using the same ui or "copy" with a set of 1,5,10,30 seconds options: 
![image](https://user-images.githubusercontent.com/62305530/139838069-88899521-e89e-4d61-94af-6c84d095d714.png)

Also, a "jump to mm:ss" option could be useful aswell, either for all videos or one by one.

**Comment by vzhd1701** [comment]
Jump options expanded, please check out the new version!

![menu](https://user-images.githubusercontent.com/5212766/140917979-1462316b-9378-41cb-8174-edbdbe120846.png)

**Comment by joshinils** [comment]
ah, so i just need to always press ctrl, got it.

could also be used when using the bar, when pressing ctrl then it is referencing the absolute beginning, not percentage
