### ISSUE TITLE
[Feature request]: balancing keyboard functionality between "all movies" and "single movie"

### ISSUE THREAD

**Issue by the-liquid-metal** [vzhd1701/gridplayer#21]
### Suggestion

There is impair keyboard functionality between "all movies" and "single movies". "all movies" missing step functionality, while "single movie" missing jump functionality. Jump functionality seems to be bloated, consume most of combination of CTRL, SHIFT, and ALT, and heavily depends on left and right button. This doesn't mean the functionality should be reduced.

It would be better if each of CTRL and ALT button are dedicated to one of "all movies" and "single movies". So users can easily remember the functionality of it's companion button. SHIFT button can be used as replacement of ALT button, or as extension 
of CTRL and ALT button. The dependancy of left and right button can be reduced by using "<" and ">" button. And if it's still not enough, "[" and "]" button can be used.

As an analitical tool, which I always use, i don't recommend GridPlayer to use single keyboard press to activate functionallity, especially buttons located at bottom row. Or may be there is an option to prevent accidentally keyboard press, so user can still enjoy single press button.

**Comment by vzhd1701** [comment]
Now all single video hotkeys are mirrored by shift+ counterparts for bulk commands.

![image](https://user-images.githubusercontent.com/5212766/175576457-c7e43a91-d027-475f-865e-4ece96bdce03.png)
