### ISSUE TITLE
[Bug]: Differen length videos are out of sync after scrolling around

### ISSUE THREAD

**Issue by joshinils** [vzhd1701/gridplayer#27]
### GridPlayer version

0.2.0

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 20.04.3 LTS

### What distribution channel are you using? [LINUX ONLY]

Snap Store

### Bug description

When playing videos of different length and skipping around or using the bar at the bottom the videos get out of sync.
menaing, the playback time is not synchronized form the start, but by the length of each video, so each video is say 42% in, not 42seconds from the start, which with different lengths would be different values.

**Comment by vzhd1701** [comment]
You have options to jump by second. Bar is intended to navigate by percentage, floating time bubble is just for reference. See https://github.com/vzhd1701/gridplayer/issues/2#issuecomment-964072837.

**Comment by joshinils** [comment]
hm, not intuitive, ok.

i would like to have an option to synchronize the time for all videos, or a "skip to beginning" for all videos option, other than using the bar and going to the beginning with sync on.

something like how youtube does it, where pressing the number keys (same function on numpad) jumps to a percentage into the video in incerements of 1/10 where 0 is 0 and 9 is one step from the end

**Comment by vzhd1701** [comment]
I added seek sync by timecode, I think it will fix this? I also added 0-9 jumps as you suggested. Please check out the new version and tell how it works for you.

![image](https://user-images.githubusercontent.com/5212766/175576914-34c28c89-2bc1-4320-b602-a79b900f40bb.png)
![image](https://user-images.githubusercontent.com/5212766/175576877-c5970c87-d7ac-4a5a-b2c3-39090560042a.png)
