### ISSUE TITLE
[Feature request]: Allow for odd number of videos to stretch/fit 

### ISSUE THREAD

**Issue by WilliUreta** [vzhd1701/gridplayer#3]
### Suggestion

If you are watching 3 videos for example, it will always generate a blank space. It would be nice to let the user choose the layout. Also it would allow for non-16:9 resolution videos to fill the whole app canvas, instead of having a squished video and a white box. 
Remove the 2xN and Nx2 limitation (Auto-Rows and Auto-Colums). See 3 videos side by side.

**Comment by vzhd1701** [comment]
![menu](https://user-images.githubusercontent.com/5212766/140917459-d0cedf4c-328b-486e-acad-95e44343dd6d.png)
Please check out the new version! Videos will now stretch to fill empty cells. To get the old behavior, you will need to uncheck "Fit Cells" in Grid submenu. Also, you can now set your preferred grid size to watch 3 videos side by side in one row or column.

**Comment by WilliUreta** [comment]
That's great, so far it works as expected. Thank you so much!
