### ISSUE TITLE
[Feature request]: Randomize videos in grid

### ISSUE THREAD

**Issue by CnBull** [vzhd1701/gridplayer#30]
### Suggestion

First, the app is perfect, it is really some great work you have done here. 

Would it be possible to randomize the location of the videos once loaded. 
So videos are running, and then by pressing a shortcut key, the videos place in the grid gets randomized with each press of the shortcut key

thanks

**Comment by vzhd1701** [comment]
Done. Now you can shuffle video blocks and have an option to shuffle on load. Please check out the new version!

![image](https://user-images.githubusercontent.com/5212766/175577151-a7178a0d-beff-4998-92c4-bb333fa73d85.png)

**Comment by CnBull** [comment]
This is excellent, thanks so much. 
This latest update has so many great features. 

Thanks for all your hard and great work :)
