### ISSUE TITLE
[Feature request]: Simultaneous playback speed.

### ISSUE THREAD

**Issue by P4nda94** [vzhd1701/gridplayer#32]
### Suggestion

Hi, 
I would need to adjust the playback speed of all videos I watch at once, instead of clicking each video. Great app though, I use it for playing multiple dance figures side by side and record it as a reminder.

**Comment by vzhd1701** [comment]
Done. Now you can control speed for all videos at once. Please check out the new version!

![image](https://user-images.githubusercontent.com/5212766/175577342-43bc1133-8e15-42ff-bbe6-a7e08b8befc0.png)
