### ISSUE TITLE
[Bug]: Webm hangs

### ISSUE THREAD

**Issue by LetMeGitDat** [vzhd1701/gridplayer#41]
### GridPlayer version

0.2.1

### What OS are you using?

Windows

### OS Version / Linux distribution

10

### Bug description

Playing WebM (vp80), displays an hourglass and hangs the video container. The container does not respond and does not display mouse over menus, preventing the user from closing the container. Other video containers still function as normal. Vp80 video tested and confirmed playable in standalone VLC and MPC.

**Comment by vzhd1701** [comment]
Could you please provide a sample video? I tested it with [VP8 WebM](https://ioncannon.net/examples/vp8-webm/demo.html) and it plays OK.

**Comment by LetMeGitDat** [comment]
Upon, restarting the player the webm indeed does seem to play... Hmm... perhaps it could be a drive read bottleneck? or out of mem? though no errors/exceptions were thrown.
