### ISSUE TITLE
[Feature request]: Sync all video timestamp

### ISSUE THREAD

**Issue by eswiig** [vzhd1701/gridplayer#44]
### Suggestion

Due to the delay in opening several videos, there will often be 1+ second difference in the playback. Yes, it's possible to skip +15/-15 secs ahead/back, but I think what the player needs is a "Sync all video playback".

Let's  say you got 3 Video Windows

Video 1: 00:00:01
Video 2: 00:00:02
Video 3: 00:00:03

Suggestion either a right click video window, or a button that lets you enter the timestamp to sync to by input: XX:XX:XX or maybe even XX:XX is enough

I would suggest an option to right click Video1 with an option to "Sync players", meaning all videos would sync to timestamp 00:00:01.

If you right clicked Video 2 and chose "Sync Players" all videos would sync timestamp to 00:00:02
Video 3, 00:00:03.

Another Example: Fast forward a video to say 04:00:00 and sync, and all other players would fast forward to 04:00:00 as well.

Possible complication: if a videos duration is less than the sync time stamp though.

Not sure if this is possible, but would appreciate if it could be considered as a feature request.

**Comment by hiroo916** [comment]
I would really like this so I can compare video encodes.  

Even better would be a "keep all videos in sync" setting so all videos would auto-sync to any changes in any timeline.
