### ISSUE TITLE
Instantaneous video desync when pressing play after changing speed on multiple videos (to same speed) 

### ISSUE THREAD

**Issue by treuherz26** [vzhd1701/gridplayer#45]
### GridPlayer version

0.2.2

### What OS are you using?

Windows

### OS Version / Linux distribution

Win 10

### Bug description

Playing three videos of same length, pause using spacebar whilst videos are synced, change speed on all videos individually using c or x, press play on all using space and sometimes one or two videos will skip 5 or 10s ahead. Also the audio often cuts out for a few seconds when pressing play after changing speeds.

**Comment by vzhd1701** [comment]
I think a lot depends on video format and other factors such as disk throughput.
