### ISSUE TITLE
[Feature request]: add support to play online videos

### ISSUE THREAD

**Issue by dv8472** [vzhd1701/gridplayer#48]
### Suggestion

Hello,
would be great, if there could be added URLs of online videos.
Plus save them as playlist as well, of course.

Thanks!

**Comment by vzhd1701** [comment]
It's done. GridPlayer can play any URL now. Please check out the new version and tell how it works for you!

**Comment by dv8472** [comment]
Unfortunatelly no, it does not work as expected.
Trying it with the Linux AppImage.
When the app is started, I dropped there the URLs and saved the playlist.

It's failing with message "Timed out to extract media track".
![image](https://user-images.githubusercontent.com/22549066/175611547-1ad351b4-92c8-42ba-9e8f-ff67b3a2c11f.png)

My playlist:
`#GRIDPLAYER
#P:{"grid_state": {"mode": "auto_rows", "is_fit": true, "size": 0}, "snapshots": {}, "seek_sync_mode": "disabled", "shuffle_on_load": false, "disable_click_pause": true, "disable_wheel_seek": true}
#V0:{"id": "95fc8fd0-34ab-4fc4-a094-9573fd3f3e10", "color": "white", "repeat_mode": "single_file", "is_start_random": false, "rate": 1.0, "aspect_mode": "fit", "is_muted": true, "scale": 1.0, "volume": 1.0, "stream_quality": "720p [95]"}
#V1:{"id": "2ba07275-9b53-4448-8630-5f17cfd2900b", "color": "white", "repeat_mode": "single_file", "is_start_random": false, "rate": 1.0, "aspect_mode": "fit", "is_muted": true, "scale": 1.0, "volume": 1.0, "stream_quality": "1080p [96]"}
#V2:{"id": "3469642c-efdc-422b-8a7e-53e8d5123305", "color": "white", "repeat_mode": "single_file", "is_start_random": false, "rate": 1.0, "aspect_mode": "fit", "is_muted": true, "scale": 1.0, "volume": 1.0, "stream_quality": "1080p [96]"}
#V3:{"id": "5b4dae03-7de3-40e7-9248-597f5cd381dd", "color": "white", "repeat_mode": "single_file", "is_start_random": false, "rate": 1.0, "aspect_mode": "fit", "is_muted": true, "scale": 1.0, "volume": 1.0, "stream_quality": "720p [95]"}
https://www.youtube.com/watch?v=xtqkslRWaQg
https://www.youtube.com/watch?v=nJdjWJr64Ps
https://www.youtube.com/watch?v=9jA-xGWo15c
https://www.youtube.com/watch?v=IdeahH9ebp8`

**Comment by vzhd1701** [comment]
What is your Linux distribution?

**Comment by dv8472** [comment]
Arch Linux, 5.15.48-1-lts, AMD Ryzen 7 5800X 8-Core Processor

**Comment by vzhd1701** [comment]
I have update the [AppImage](https://github.com/vzhd1701/gridplayer/releases/download/v0.3.0/GridPlayer-0.3.0-x86_64.AppImage). Please try it out and tell how it works for you.

**Comment by dv8472** [comment]
Much better. Thank you!
In case you're interested, the following output is produced in the CLI when I opened the playlist provided:

```
$ ./GridPlayer-0.3.0-x86_64.AppImage 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
```

**Comment by vzhd1701** [comment]
Do you have nvidia GPU?

**Comment by dv8472** [comment]
yes

**Comment by vzhd1701** [comment]
Do you have libvdpau_nvidia.so installed?

**Comment by dv8472** [comment]
Yes I do.
```
# pacman -Qo /usr/lib/vdpau/libvdpau_nvidia.so*
/usr/lib/vdpau/libvdpau_nvidia.so is owned by nvidia-utils 515.48.07-2
/usr/lib/vdpau/libvdpau_nvidia.so.1 is owned by nvidia-utils 515.48.07-2
/usr/lib/vdpau/libvdpau_nvidia.so.515.48.07 is owned by nvidia-utils 515.48.07-2

# pacman -Ss nvidia-utils
extra/nvidia-utils 515.48.07-2 [installed]
    NVIDIA drivers utilities
multilib/lib32-nvidia-utils 515.48.07-1 [installed]
    NVIDIA drivers utilities (32-bit)
```

But, isn't the purpose of linux images like AppImage to bring everything within the image?

**Comment by vzhd1701** [comment]
Try setting it's parent directory to `VDPAU_DRIVER_PATH` variable before running GridPlayer
```
export VDPAU_DRIVER_PATH=/usr/lib/vdpau
```

**Comment by dv8472** [comment]
Great.
Now the only what is remaining is that `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`, [but this probably ain't supported](https://bbs.archlinux.org/viewtopic.php?pid=1941680#p1941680).

Nevertheless, thank you very much for your effort!

**Comment by dv8472** [comment]
I just had a failure:
```
Traceback (most recent call last):
  File "/tmp/.mount_GridPlbDbLWj/usr/lib/python3.8/site-packages/gridplayer/widgets/video_frame_vlc_base.py", line 251, in snapshot_taken
    Path(snapshot_file).unlink()
  File "/tmp/.mount_GridPlbDbLWj/usr/lib/python3.8/pathlib.py", line 1316, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmptx8r40yu/snapshot.png'
```

**Comment by vzhd1701** [comment]
When you unpaused a stream? Was the paused frame ok?

**Comment by dv8472** [comment]
The app is running (the same playlist, have just renamed the frames) in background - down left corner, and I was doing something else in the browser.
When I suddenly noticed freeze of image of the down right grid image in the app.
Then the failure & crash followed.
I don't think I paused it, at least I do not remember a step like that.
However, now, when testing it, pause and unpause do not show any problems.
I will keep you informed, if anything similar happens again.
