### ISSUE TITLE
[Feature request]: Create "master" time bar

### ISSUE THREAD

**Issue by WilliUreta** [vzhd1701/gridplayer#5]
### Suggestion

If the videos have equal length, show a general time bar so all the videos can be scrolled from one time bar. Maybe it could be a setting in preferences: If all videos have equal length, set master time-bar.

Thanks!

**Comment by vzhd1701** [comment]
I have implemented it as a flag that will allow you to seek in sync using the progress bar of any video. Would you please check out version 0.1.5 to see it in action and say how it works for you?
![Clipboard Image](https://user-images.githubusercontent.com/5212766/142889375-25958d9c-c25b-41f4-853e-71cbff37f428.png)

**Comment by k-y-a** [comment]
Work great for me, it not only sync mouse click but also keyboard seeking (Right/Left arrow, etc)
