### ISSUE TITLE
[Feature request]: Playing three vertical videos

### ISSUE THREAD

**Issue by TorATB** [vzhd1701/gridplayer#50]
### Suggestion

First, your GridPlayer is awesome! I have a playlist with vertical videos, it would be really great if the player displayed the three videos next to each other. If I try playing three videos, even when selected "Columns first", it will add the third video as "quad split" - view...

**Comment by vzhd1701** [comment]
Try setting Grid size to 3

![image](https://user-images.githubusercontent.com/5212766/172592812-fc1f1907-f220-4e2c-b58d-e47c475087ed.png)

**Comment by TorATB** [comment]
Wow. Nice. 😁😁
  

  

  
  
-Tor
  

  

        
  
  
>
