### ISSUE TITLE
[Bug]: Aspect Mode doesn't seem to work when opening from playlist

### ISSUE THREAD

**Issue by dv8472** [vzhd1701/gridplayer#58]
### GridPlayer version

GridPlayer-0.3.0-x86_64.AppImage

### What OS are you using?

Linux

### OS Version / Linux distribution

Arch

### What distribution channel are you using? [LINUX ONLY]

AppImage

### Bug description

Example grid: two frames on top, one in the bottom.
Even if I set the "Aspect mode:**none**" in Settings or is saved in the playlist, when I open the playlist, the bottom one is always loaded in "Aspect fit" mode.
![image](https://user-images.githubusercontent.com/22549066/176988598-a615ec45-6567-44a5-960d-d85c87b80975.png)

When loaded the playlist, it is showing "Aspect none":
```
#GRIDPLAYER
#P:{"grid_state": {"mode": "auto_rows", "is_fit": true, "size": 0}, "window_state": [false, false, "AdnQywADAAAAAAAAAAADEAAAAoUAAASNAAAAAwAAAyMAAAKCAAAEigAAAAAAAAAAB4AAAAADAAADIwAAAoIAAASK"], "snapshots": {}, "seek_sync_mode": "disabled", "shuffle_on_load": false, "disable_click_pause": true, "disable_wheel_seek": true}
#V0:{"id": "95fc8fd0-34ab-4fc4-a094-9573fd3f3e10", "title": "Africam - Tau", "color": "white", "repeat_mode": "single_file", "is_start_random": false, "rate": 1.0, "aspect_mode": "none", "is_muted": true, "scale": 1.0, "volume": 1.0, "stream_quality": "720p [95]"}
#V1:{"id": "2ba07275-9b53-4448-8630-5f17cfd2900b", "title": "Africam - Olifants River", "color": "white", "repeat_mode": "single_file", "is_start_random": false, "rate": 1.0, "aspect_mode": "none", "is_muted": true, "scale": 1.0, "volume": 1.0, "stream_quality": "1080p [96]"}
#V2:{"id": "5b4dae03-7de3-40e7-9248-597f5cd381dd", "title": "Africam - Nkorho", "color": "white", "repeat_mode": "single_file", "is_start_random": false, "rate": 1.0, "aspect_mode": "none", "is_muted": true, "scale": 1.0, "volume": 1.0, "stream_quality": "720p [95]"}
https://www.youtube.com/watch?v=xtqkslRWaQg
https://www.youtube.com/watch?v=nJdjWJr64Ps
https://www.youtube.com/watch?v=IdeahH9ebp8
```
![image](https://user-images.githubusercontent.com/22549066/176988601-09ccaf4a-95b4-4a3d-8e6d-949138738c6f.png)

But it does not work:
![image](https://user-images.githubusercontent.com/22549066/176988620-18aa554e-e4a8-4d3e-9c08-12386b86fc61.png)

However, when I click the already selected "Aspect none" again, only after that the aspect changes to the "Aspect none".
![image](https://user-images.githubusercontent.com/22549066/176988665-68dcc8c2-2465-4fda-98d2-95c7338d7254.png)

**Comment by vzhd1701** [comment]
Could you try resizing window and see if it readjusts to the proper aspect?

**Comment by dv8472** [comment]
nope, it did not
![image](https://user-images.githubusercontent.com/22549066/176989605-65f30d2f-75d9-4666-9891-cf4d45f13d38.png)

**Comment by lekma** [comment]
can confirm behaviour.
shouldn't "aspect_mode" be `null` instead of `"none"` in the playlist file?

**Comment by vzhd1701** [comment]
> maybe call it "native"?

Good idea.

**Comment by vzhd1701** [comment]
Fixed. Please check out the new version.

**Comment by dv8472** [comment]
Looks good, thank you!
