### ISSUE TITLE
[Bug]: (10292) | PlayerProcessSingleVLCHW | ERROR | Video track is missing!

### ISSUE THREAD

**Issue by k-y-a** [vzhd1701/gridplayer#6]
### GridPlayer version

0.1.3

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10 64-bit

### Bug description

> After drag&drop .TS file (which is working in VLC) in log file we can see:

> 2021-11-14 14:23:35,138 (10292) | PlayerProcessSingleVLCHW | ERROR | Video track is missing!

https://www.videohelp.com/software/GridPlayer/reviews

---

To be honest, just want to tell you that there is now a link on VideoHelp, I notice the first review having an issue but he/she didn't consider reporting it in the right place. But I thought if I post it here it might help you bug fix this (if that possible) based on information provided; which isn't much.

**Comment by k-y-a** [comment]
I noticed this changelogs...

>  Version history / Release notes / Changelog

> v0.1.4
> Bug Fixes
> fix error when opening some formats (ts, wmv) (4c8b19c)

So it might been fixed already?

**Comment by vzhd1701** [comment]
Yes, I saw that review. Yes, it's already fixed in 0.1.4 :)
