### ISSUE TITLE
[Feature request]: Quick paste function

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#63]
### Suggestion

Hello, since we use the magnificent GirdPlayer for streaming content, it becomes a bit tiring and boring to always click on the right button / add url/paste, it will be great to add an option that automatically detects the url in the clipboard and the media player plays it directly without clicking, or add a button in the main bar in the main window "paste url and automatically play video", thank you !

**Comment by vzhd1701** [comment]
Added in version 0.5.0

**Comment by trimechee** [comment]
Awesome !! Thank you so much :) 🥇
