### ISSUE TITLE
Plugin VLC 3DYD Youtube Source

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#64]
Hello, "3DYD Youtube Source" which is a set of plugins and has many amazing features like download media data independently from playback, manual quality selection before playback start, HLS live streams support, DASH streams support (video and audio goes from separate streams), support for audio-only playback.....

and it works only for video players which support playback using DirectShow like "potplayer" and "mpc-hc" (or mpc-be) and they worked for me when i tried this software,  an exception is VLC, for which is available separate plugin. : I admit, I installed the vlc plugin from "3DYD Youtube Source" but it didn't work with VLC player, I don't know if I did things wrong, so since our beloved GirdPlayer is compatible with VLC player, can GirdPlayer add an option to embed vlc plugin of "3DYD Youtube Source" so GirdPlayer will have even more outstanding options for streaming !

Thanks a lot !

https://ys.3dyd.com/download/

https://ys.3dyd.com/home/

Latest VLC plugin version details : 

preliminary support for VLC 3.0. Functionality and installation are the same as in VLC 2.2. Additionally added support for multiple ABI versions within one plugin. That means there will be single DLL plugin file for all VLC versions (per platform) instead of individual plugins for every VLC version.

https://ys.3dyd.com/changelog/vlc/

for developers, may it can help to integrate vlc plugin to GirdPlayer : 

https://ys.3dyd.com/developers/

**Comment by vzhd1701** [comment]
Thank you for the suggestion, but I already have yt-dlp integrated which serves the same purpose. Also this plugin only works for Windows, while my GridPlayer is cross-platform.

**Comment by trimechee** [comment]
I understand , thank you :)  i think "3DYD Youtube Source" has its own internal settings which is different and not based on yt-dlp and may offer options not available through yt-dlp, and it also offers external settings which may be based on yt-dlp....for example there is support of HLS live streaming , full video streaming buffer because of download media data independently from playback....

i tried to add vlc plugin of 3DYD Youtube Source to GirdPlayer but i don't fond the plugin folder, because 
i go to help section: "Extract appropriate plugin version (x86 or x64) to vlc/plugins/access directory (since it is 'access'-type plugin, however you can place it anywhere under plugins directory). Well, that's it.

To ensure that it is recognized by VLC go to menu Tools Plugins and extensions Plugins and check plugins list, '3DYD Youtube Source' should be listed there.

Note, this is not standalone plugin. It requires 3DYD Youtube Source filter to be installed in the system."


https://ys.3dyd.com/help/vlc_plugin/



i go to the GirdPlayer folder and ididn't find plugin folder, please it will be great if GirdPlayer add plugin folder so we can add "vlc plugin" of "3DYD Youtube Source" to GordPlayer, thank you :)

**Comment by trimechee** [comment]
And it's good thing Girdplayer is cross-platform, I would like to use linux but sometimes there are hardware compatibility issues and driver issue so most people have to use windows hoping more brands natively support linux distro !

**Comment by vzhd1701** [comment]
I am sorry, but this plugin is not going to work with GridPlayer. Even if you manage to install it into libVLC plugins, youtube links are handled directly by yt-dlp inside GridPlayer before going to VLC part.

**Comment by trimechee** [comment]
I understand, it does not matter, thank you for listening to me and helping me :)
