### ISSUE TITLE
[Feature request]: Seek time by dragging

### ISSUE THREAD

**Issue by k-y-a** [vzhd1701/gridplayer#7]
### Suggestion

v0.1.4

Feature: Hold+drag mouse and seek time

Can the timer bar be made so that when you hold+drag it will seek time (back and forward). Currently the default behavior when you hold and drag (anywhere) it go into "layout moving".

This will make it easier to seek video timer instead of having to keep clicking on a timer bar at different position. Drag to seek time can be found in the VLC and various other player (MPC-HC/BE for example)

**Comment by vzhd1701** [comment]
I have implemented it in version 0.1.5. Please check it out and say how it works for you!

**Comment by k-y-a** [comment]
Work great! Tested it for a few minutes with 4 .mkv video.
