### ISSUE TITLE
[Feature request]: Group speedup

### ISSUE THREAD

**Issue by SwaggerNiels** [vzhd1701/gridplayer#74]
### Suggestion

Hello vzhd1701,

Love this piece of software!
I use it to observe the many recordings I have of the electroplating of microelectrodes.
It is a great tool to just view or also present.

Some features that would be awesome:
- Speedup all the videos at once (or perhaps even a selection of them)
- Sync all the video timelines
- Render the complete playlist as a single video/gif

2 Questions:
Why does GridPlayer keep running in the background even when the program is closed?
Why does the installation have "websockets" and "cryptodome" folders?

**Comment by vzhd1701** [comment]
> Speedup all the videos at once (or perhaps even a selection of them)

![image](https://user-images.githubusercontent.com/5212766/180017903-e211fd74-43c2-4f5f-b2ef-399e68c471c2.png)

> Sync all the video timelines

![image](https://user-images.githubusercontent.com/5212766/180018140-a59cd972-f2a6-4ab1-97c0-a9c87a0254cd.png)

> Why does GridPlayer keep running in the background even when the program is closed?

This shouldn't be happening. What OS are you using?

> Why does the installation have "websockets" and "cryptodome" folders?

These are dependencies for yt-dlp

**Comment by SwaggerNiels** [comment]
> Sync all the video timelines
> Speedup all the videos at once (or perhaps even a selection of them)

Ah yes i see now!
Thank you

> This shouldn't be happening. What OS are you using?

I am using Windows 11

> Render the complete playlist as a single video/gif

Do you think this is simple to implement? Otherwise I will resort to screen-capturing using [ScreenToGif](https://github.com/NickeManarin/ScreenToGif), which also works I guess.

Anyway thanks for the quick response.

**Comment by vzhd1701** [comment]
> Render the complete playlist as a single video/gif
> Do you think this is simple to implement? Otherwise I will resort to screen-capturing using [ScreenToGif](https://github.com/NickeManarin/ScreenToGif), which also works I guess.

It won't be simple, I can't promise to get it out soon.

How often do you get this glitch when it is running in the background?

**Comment by SwaggerNiels** [comment]
Update:
I am using Windows 11, your application hosts 
- 1 process while running w/o a video open
- 2 processes while running w/ a video open

![afbeelding](https://user-images.githubusercontent.com/58084010/180024095-cbe16b4b-9969-4999-9ad2-a297bd3f9efc.png)

Scenario A: I close the video and then close the program
- no processes open

Scenario B: I **do not** close the video and directly close the program
- 1 process remains

This happens reliably.
So I guess the videos should close automatically before the program closes. For now I will do it myself ;)

**Comment by vzhd1701** [comment]
I hope you don't mind if I close this issue and open 2 others - one for process bug and one for gif record feature?
