### ISSUE TITLE
[Bug]: Background process remains after application is closed

### ISSUE THREAD

**Issue by vzhd1701** [vzhd1701/gridplayer#75]
I am using Windows 11, your application hosts 
- 1 process while running w/o a video open
- 2 processes while running w/ a video open

![afbeelding](https://user-images.githubusercontent.com/58084010/180024095-cbe16b4b-9969-4999-9ad2-a297bd3f9efc.png)

Scenario A: I close the video and then close the program
- no processes open

Scenario B: I **do not** close the video and directly close the program
- 1 process remains

This happens reliably.
So I guess the videos should close automatically before the program closes. For now I will do it myself ;)

_Originally posted by @SwaggerNiels in https://github.com/vzhd1701/gridplayer/issues/74#issuecomment-1190443332_

**Comment by Lucifie** [comment]
Have seen this too when the application crashes. Then a few of the processes stay open and you even can hear the sound but the main app is gone.

**Comment by kirillall** [comment]
v0.4.3-win64-portable background processes is still running after player is closed.
btw: player is awesome!!! Thank you!

**Comment by vzhd1701** [comment]
Should be fixed in the new version.
