### ISSUE TITLE
[Feature request]: Automatically load next file in folder

### ISSUE THREAD

**Issue by daveeddiggss** [vzhd1701/gridplayer#8]
### Suggestion

Amazing work, really good player, I would love it if once a video has finished, it moves on to the next video in the folder or a playlist

**Comment by vzhd1701** [comment]
Done. Now you have 3 loop options and the ability to jump to next/previous file.
![Clipboard Image](https://user-images.githubusercontent.com/5212766/147658276-c6d44a6a-76c3-4df2-b68b-6dc1cf699717.png)
![Clipboard Image (1)](https://user-images.githubusercontent.com/5212766/147658382-37033352-5869-4359-8c59-16ebd95a2a10.png)
