### ISSUE TITLE
Streamlink plugins 

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#83]
### Suggestion

Hello, archlinux of streamlink said :" Support for various streaming services is provided by plugins, which can be easily added if needed. A lot of popular video streaming services are supported out of the box, including Dailymotion, Livestream, Twitch, UStream, YouTube Live and many more; see [Plugins](https://streamlink.github.io/plugins.html) for the full list."

So, did Gridplayer add all streamlink plugins or just add some plugins?

it will be great if Gridplayer adds all these plugins by default especially for tv channels, or offer an option to manually add streamlink plugins but with a ban of adding plugins from disgusting vulgar porn sites which are unfortunately present in the list of streamlink plugins, because porn sites destroy society and spread diseases and vice and perversity and we must ban the plugins of these seedy sites.....

Thanks a lot !

**Comment by vzhd1701** [comment]
Yes, all plugins from the official streamlink list are included.

**Comment by trimechee** [comment]
Magnificent beautiful! thank you very much for making this outstanding software !!
