### ISSUE TITLE
[Bug]: Error loading Python DLL

### ISSUE THREAD

**Issue by johnnysmith65** [vzhd1701/gridplayer#9]
### GridPlayer version

0.1.4

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10 64bit

### Bug description

Version 0.1.4 doesn't work in Windows 10.  It has a fatal error about loading a python module upon startup. Neither the installer version or portable version works.

Error message is:
Error loading Python DLL
c:\.......\GridPlayer\python38.dll.
LoadLibrary: The specified module could not be found.

**Comment by johnnysmith65** [comment]
Installing Python and having Python be in the system PATH environment variable make the issue go away.

**Comment by vzhd1701** [comment]
Thank you for reporting the bug! I was able to reproduce it. Python is bundled with the player and you shouldn't need to install any external dependencies. I have made a mistake on the packaging stage. I will release a fixed version soon. For now as a workaround you can copy `VCRUNTIME140.dll` and `VCRUNTIME140_1.dll` from `lib` directory to the root of GridPlayer directory where `GridPlayer.exe` is.

**Comment by vzhd1701** [comment]
It should be fixed in 0.1.5. Could you please try uninstalling Python and running it again with new version?

**Comment by johnnysmith65** [comment]
Both the installer and portable version of 0.1.5 for Windows now work without installing Python.   Testing was done in a Windows 10 64bit sandbox with nothing else installed.

Thank you for your handy program.
