### ISSUE TITLE
[Feature request]: Display rotation of individual videos

### ISSUE THREAD

**Issue by johnnysmith65** [vzhd1701/gridplayer#90]
### Suggestion

Being able to set display rotation on a per video basis would be a nice enhancement.

**Comment by sum1game** [comment]
There is also a need

**Comment by sum1game** [comment]
Dear author, it's wonderful to see your ongoing updates to this project on GitHub. We fully support @johnnysmith65  suggestion regarding the video rotation feature, as it has been immensely helpful for our work and usage. If it were possible to assign a shortcut key to this feature, it would further enhance its convenience. 
We kindly ask if you could consider adding this enhancement to the program when you have the chance. It would greatly benefit our work and usage,Thanks for the update. @vzhd1701

**Comment by LiberiFatali** [comment]
From my search, this is possible. However, there is one downside: the video needs to be restarted when setting rotation. Is that ok?

**Comment by sum1game** [comment]
I think this small flaw doesn't matter, so there's no problem.

**Comment by johnnysmith65** [comment]
Restarting the video after rotation would be fine.

**Comment by sum1game** [comment]
@vzhd1701 Dear author, I tested the rotation function of version 0.5.1 on a WIN10 environment. Whether it is a single video or ALL video, the 90, 180, 270, horizontal flip, mirror flip, and other functions did not actually change the picture, only reloaded the video.

**Comment by sum1game** [comment]
No problem, I will complete this operation now. Please wait a moment.

**Comment by sum1game** [comment]
In order to provide the author with more testing data, I opened two videos, 1.MP4 and 2.MP4. For the individual video 1.MP4, I performed 90, 180, 270, horizontal flip, and mirror flip operations in sequence. For the combined videos 1.MP4 and 2.MP4, there were also multiple relevant rotation operations. I hope this data is helpful to you.
https://www.mediafire.com/file/rz0jbfztpo2lznk/gridplayer2.log/file

**Comment by sum1game** [comment]
@vzhd1701 The related functions for video rotation are now working properly, thanks to the author's fix! However, there are still some issues with the display, especially in the cases of rotate90 and rotate270 (transpose, anti-transpose), where the aspect None affects the display and causes distortion. I believe this may be due to the resolution not matching the size after rotation. For example, for a 1280x720 video displayed after rotating 90/270 degrees, the new resolution should be 720x1280. Currently, the program still plays the video based on the original resolution of 1280x720, which causes the screen to be squeezed.

**Comment by LiberiFatali** [comment]
> @vzhd1701 The related functions for video rotation are now working properly, thanks to the author's fix! However, there are still some issues with the display, especially in the cases of rotate90 and rotate270 (transpose, anti-transpose), where the aspect None affects the display and causes distortion. I believe this may be due to the resolution not matching the size after rotation. For example, for a 1280x720 video displayed after rotating 90/270 degrees, the new resolution should be 720x1280. Currently, the program still plays the video based on the original resolution of 1280x720, which causes the screen to be squeezed.

@sum1game Could you share the example video to test this?

**Comment by sum1game** [comment]
This phenomenon can be reproduced with any video of 1280*720 resolution, without the need for a specific video. Simply perform a rotate90 operation on any video to see the squeezing effect!

**Comment by LiberiFatali** [comment]
> This phenomenon can be reproduced with any video of 1280*720 resolution, without the need for a specific video. Simply perform a rotate90 operation on any video to see the squeezing effect!

I haven't been able to reproduce this. Perform a rotate operation (90, 270...) is fine.

Only when I change the Aspect (i.e from Fit -> None) after rotating the image is stretched. And if I do rotation again, the video gets back to normal.

**Comment by sum1game** [comment]
Yes, as I mentioned before, combining the "aspect None" setting with the rotation function can cause image distortion. However, during my testing today, I found that even if the setting is changed to i.e from Fit "aspect Fit" the video is rotated 90 degrees, image distortion can still occur. If you want to discover more, you can try playing two 1080p or 3840p videos simultaneously, and the distortion will become more apparent with higher resolutions. To fix this bug, it is necessary to adjust the display resolution or aspect ratio while rotating the video.

**Comment by LiberiFatali** [comment]
> Yes, as I mentioned before, combining the "aspect None" setting with the rotation function can cause image distortion. However, during my testing today, I found that even if the setting is changed to i.e from Fit "aspect Fit" the video is rotated 90 degrees, image distortion can still occur. If you want to discover more, you can try playing two 1080p or 3840p videos simultaneously, and the distortion will become more apparent with higher resolutions. To fix this bug, it is necessary to adjust the display resolution or aspect ratio while rotating the video.

Could you record a short clip that capture this problem?
