### ISSUE TITLE
[Bug]: Crash on startup since 0.2.1 on MacOS

### ISSUE THREAD

**Issue by dguido** [vzhd1701/gridplayer#93]
### GridPlayer version

0.2.2 - 0.4.3

### What OS are you using?

MacOS

### OS Version / Linux distribution

MacOS 12.5.1

### Bug description

Trying to run any recent version of GridPlayer on MacOS 12.5.1 results in the following error message:

<img width="256" alt="Screen Shot 2022-09-05 at 4 52 23 PM" src="https://user-images.githubusercontent.com/294844/188511522-10b778b6-e2cb-47ca-828c-5a3213d94821.png">

0.2.1 seems to work.

**Comment by vzhd1701** [comment]
Have you tried this workaround?
```shell
$ sudo xattr -rd com.apple.quarantine /Applications/GridPlayer.app
```

**Comment by dguido** [comment]
That gets GridPlayer to launch, but trying to play any video simply causes it to get stuck on "Buffering".

**Comment by usmajeed** [comment]
> 

This

**Comment by dguido** [comment]
I tested each version back from 0.4.3. It appears to have broken between 0.2.2 and 0.3.0.

**Comment by dynamicpacket** [comment]
I can confirm that on Mac OS 12.4 after using xattr, it will get stuck on buffering. not sure whats causing this, using latest build

**Comment by vzhd1701** [comment]
Version 0.5.1 should work in MacOS.
