### ISSUE TITLE
[Feature request]: Add option to randomize opening four/eight files from a folder/playlist file/text file. with shuffle option.

### ISSUE THREAD

**Issue by ammoryyy** [vzhd1701/gridplayer#96]
Add option to randomize opening four/eight/certain no of files from a HDD/folder/playlist file/text file. with shuffle option.

**Comment by vzhd1701** [comment]
Added in version 0.5.0

**Comment by Mageign** [comment]
Doesn't work for me on windows 11 pro, can't drag drop a folder/drive or open it through menu, Shuffle option only working when patiently waiting for a video to finish by itself. v0.5.0 portable.
